# test_workflow.yml

name: Run All Tests

on:
push:
branches:
- feature/**
pull_request:
branches:
- main

jobs:
test:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v3

```
  - name: Set up Node.js
    uses: actions/setup-node@v3
    with:
      node-version: 18

  - name: Install dependencies
    run: npm install

  - name: Run test suite
    run: npm run test

  - name: Upload test results (if needed)
    if: failure()
    run: |
      echo "## ❌ TEST FAILED" > test-report.md
      echo "Please review the errors above and fix them before merging." >> test-report.md

  - name: Save report artifact
    uses: actions/upload-artifact@v3
    if: failure()
    with:
      name: test-report
      path: test-report.md

```